
export const ITEMS_PER_PAGE = 10;
export const MESSAGE_CREATING = 'MESSAGE_CREATING';
export const MESSAGE_CREATE_SUCCESS = 'MESSAGE_CREATE_SUCCESS';
export const MESSAGE_CREATE_ERROR = 'MESSAGE_CREATE_ERROR';
